version: 3

vars:
  LOCAL_BIN:
    sh: echo "$(pwd)/bin"
  PATH:
    sh: echo "{{ .LOCAL_BIN }}:{{ env "PATH" }}"

env:
  GOOSE_DBSTRING: dbname=postgres user=postgres password=postgres host=127.0.0.1 port=5432 sslmode=disable

tasks:
  generate:
    deps:
      - task: bin-deps
    cmds:
      - PATH="{{ .PATH }}" oapi-codegen -config ./configs/openapi/error.yaml ./api/common/error.openapi.yaml
      - PATH="{{ .PATH }}" oapi-codegen -config ./configs/openapi/auth.yaml ./api/v1/auth.openapi.yaml
      - PATH="{{ .PATH }}" oapi-codegen -config ./configs/openapi/portfolio.yaml ./api/v1/portfolio.openapi.yaml
      - PATH="{{ .PATH }}" oapi-codegen -config ./configs/openapi/user.yaml ./api/v1/user.openapi.yaml
      - PATH="{{ .PATH }}" go generate ./...
      - go mod tidy
      - go mod vendor
  test:
    cmds:
      - go test -tags integration -coverprofile covertmp.out ./...
      - grep -v 'server\.gen\.go' covertmp.out > cover.out
      - go tool cover -func cover.out
  bin-deps:
    cmds:
      - test -d {{ .LOCAL_BIN }} || mkdir {{ .LOCAL_BIN }}
      - GOBIN={{ .LOCAL_BIN }} go install tool
      - GOBIN={{ .LOCAL_BIN }} go install github.com/pressly/goose/v3/cmd/goose@v3.26.0
  migration:
    cmds:
      - PATH="{{ .PATH }}" goose --dir migrations {{ .CLI_ARGS }}
