package: portfolio
output: internal/api/v1/portfolio/server.gen.go
generate:
  models: true
  chi-server: true
output-options:
  skip-prune: true
import-mapping:
  ../common/error.openapi.yaml: github.com/buffi-buchi/invest-compass/backend/internal/api
