openapi: 3.0.0
info:
  title: Securities API
  description: Securities API describes handlers to manage securities
  version: 0.1.0

servers:
  - url: http://localhost:8080/api
    description: Server for local development

security:
  - BearerAuth: [ ]

paths:
  /v1/securities/:
    get:
      operationId: GetSecurities
      tags:
        - securities
      description: Returns list of securities
      parameters:
        - $ref: '#/components/parameters/IndexIdQuery'
      responses:
        '200':
          $ref: '#/components/responses/SecuritiesListResponse'
        'default':
          $ref: '../common/error.openapi.yaml#/components/responses/ErrorResponse'

components:
  parameters:
    IndexIdQuery:
      name: index_id
      in: query
      required: false
      description: Filter securities by index identifier (e.g., IMOEX)
      schema:
        type: string
        example: "IMOEX"
  responses:
    SecuritiesListResponse:
      description: Successful operation - list of securities
      content:
        application/json:
          schema:
            type: object
            properties:
              securities:
                  type: array
                  items:
                    $ref: '#/components/schemas/Security'
  schemas:
    Security:
      type: object
      required:
        - ticker
        - name
        - current_price
      properties:
        shortName:
          type: string
          example: "Аэрофлот"
          maxLength: 20
        ticker:
          type: string
          maxLength: 20
          example: "AAPL"
          description: Trading symbol of the security
        weight:
          type: number
          example: 15.4

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
