openapi: 3.0.0
info:
  title: Securities API
  description: Securities API describes handlers to manage securities
  version: 0.1.0

servers:
  - url: http://localhost:8080/api
    description: Server for local development

security:
  - BearerAuth: [ ]

paths:
  /v1/securities/:
    get:
      operationId: GetSecurities
      tags:
        - securities
      description: Returns list of securities
      parameters:
        - $ref: '#/components/parameters/IndexIdQuery'
      responses:
        '200':
          $ref: '#/components/responses/SecuritiesListResponse'
        'default':
          $ref: '../common/error.openapi.yaml#/components/responses/ErrorResponse'
components:
  parameters:
    IndexIdQuery:
      name: index_id
      in: query
      required: false
      description: Filter securities by index identifier (e.g., IMOEX)
      schema:
        type: string
        example: "IMOEX"
  responses:
    SecuritiesListResponse:
      description: Successful operation - list of securities
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Security'
  schemas:
    Security:
      type: object
      required:
        - ticker
        - name
        - current_price
      properties:
        isin:
          type: string
          minLength: 12
          maxLength: 12
          example: "US0378331005"
          description: International Securities Identification Number
        ticker:
          type: string
          maxLength: 20
          example: "AAPL"
          description: Trading symbol of the security
        name:
          type: string
          maxLength: 200
          example: "Apple Inc."
          description: Name of the security
        current_price:
          type: number
          format: float
          minimum: 0
          example: 150.75
          description: Current price of the security


  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
