components:
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string

  responses:
    ErrorResponse:
      description: Error response for codes 4** and 5**
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
